import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/HeaderComponent.module.css";
import imageProfile from "../../assets/ProfileImage.png";

export default function HeaderComponent() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.background} />
        <nav style={{ display: "flex" }}>
          <Link href="/">
            <a
              className={styles.logoBackground}
              aria-label="Redirect to home page"
            />
          </Link>
          <div className={styles.navigation}>
            <div className={styles.navigationLeft}>
              <menu>
                <li>
                  <Link href="/">
                    <a href="/" type="button" className="button">
                      Create Your Nanny Share
                    </a>
                  </Link>
                </li>
                <li>
                  <Link href="/">
                    <a href="/" type="button" className="button">
                      Browse Shares
                    </a>
                  </Link>
                </li>
                <li>
                  <Link href="/">
                    <a type="button" className="button">
                      Our Story
                    </a>
                  </Link>
                </li>
              </menu>
            </div>
            <div className={styles.navigationRight}>
              <ul>
                <li
                  type="button"
                  className="button"
                  style={{ backgroundColor: "#00C88C" }}
                >
                  <h5>Become a Nanny Share Host</h5>
                </li>
                <li type="button" className="button">
                  <h5>Sign in</h5>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <section
          style={{
            display: "grid",
            placeItems: "center",
            flexGrow: "1",
          }}
        >
          <div className={styles.highlight}>
            <div className={styles.highlightLeft}>
              <h1 className={styles.h1}>
                Easily create or join a local nanny share with Hapu
              </h1>
              <p>
                Hapu is Airbnb for nanny share. Share your home, nanny and costs
                and create new flexible, affordable solutions in childcare.
              </p>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  margin: "48px 0",
                }}
              >
                <button className={styles.buttonTotalRadius}>▶</button>
                <a style={{ padding: "0 16px" }}>
                  See hapu in action (27 seconds)
                </a>
              </div>
            </div>
            <div>.</div>
          </div>
        </section>
      </header>
      <footer className={styles.footer}>
        <Image
          src={imageProfile}
          className={styles.imageProfile}
          alt="Picture of a nanny"
          width="56px"
          height="56px"
        />
        <Link href="/">
          <a className="a" style={{ margin: "0 8px" }}>
            Sarah’s day care available now in North Sydney
          </a>
        </Link>
        <p>Wednesday, Thursday, Friday - 7:30 - 5:30</p>
      </footer>
    </>
  );
}
